source "https://rubygems.org"

ruby "~> 3.4.0"

gem "jekyll", "~> 4.3.4"
gem "webrick" # Required for Ruby 3.0+
gem "base64" # Required for Ruby 3.4+
gem "csv" # Required for Ruby 3.4+
gem "logger" # Required for Ruby 3.4+

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-sass-converter", "~> 3.0"
end 